"""40m SOS (Small Optic Suspension) — 6-DOF rigid-body-on-wires plant.

The 40m SOS is an initial-LIGO single-stage suspension: one fused-silica optic hung on a
wire loop, actuated by five OSEM coil-magnet pairs (UL/UR/LR/LL/SIDE). This module builds
its continuous 6-DOF state-space in the twin's Euler basis (L T V R P Y), as a
``control.StateSpace`` — the Stage-0 artifact of the 40m SOS sysID campaign.

Why the model is built here rather than harvested
-------------------------------------------------
The obvious donor, ``simplant``'s ``lib/sus_single_plant.mdl`` (recovered in
``digital_twin/simplant-salvage/``), is generated by ``scripts/sus_plant_TM_coef.m`` from
LIGO DCC **T000134** parameters. Its *optic* is 40m-SOS-class (m = 0.24 kg vs. 0.243 kg from
the 40m geometry), and its longitudinal/side modes land within 0.1% of the 40m measurement —
but it is a **4-DOF** model (x, pitch, yaw, y) with no wire-stretch degree of freedom, so it
has no vertical and no roll, and its pitch/yaw run 23-29% high because ``b``/``R1``/``R2`` are
T000134's rather than the 40m's. See that directory's README for the measured comparison.

So the optic inertia comes from the known 40m geometry, and the *suspension* parameters that
T000134 cannot supply are pinned by requiring the six eigenmodes to reproduce the measured
40m set. That makes the mode table a construction target for five of the six DOF — and
``T`` (side) a genuine prediction, since nothing is fitted to it.

Conventions
-----------
* DOF order **L T V R P Y** = longitudinal, transverse (side), vertical, roll, pitch, yaw,
  matching ``twin`` and ``mimo_campaign.assemble_campaign``.
* Optical axis is **x** (longitudinal); the optic is a cylinder about it.
* Inputs are forces/torques per DOF; outputs are displacements/angles per DOF.
* Damping is the repo-wide structural convention ``Q = 50`` (``sus_modal.DEFAULT_STRUCTURAL_Q``,
  ``plant_loader``'s ``structural_q``) applied per mode as ``gamma = omega / Q``. It is a
  *convention*, not a 40m measurement — do not report it as an identified quantity.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
import control
from scipy.optimize import fsolve

G = 9.806  # m/s^2

DOFS = ("L", "T", "V", "R", "P", "Y")
_IDX = {d: i for i, d in enumerate(DOFS)}

DEFAULT_STRUCTURAL_Q = 50.0

#: Measured 40m SOS eigenmodes [Hz] — the Stage-0 feasibility gate.
#: Source: campaign handoff note (`notes/40m-sos-campaign-handoff-2026-07.md`).
MEASURED_MODES_HZ: dict[str, float] = {
    "L": 1.0,
    "T": 1.0,
    "V": 16.0,
    "R": 16.0 * math.sqrt(2.0),
    "P": 0.6,
    "Y": 0.7,
}


@dataclass(frozen=True)
class SOSOptic:
    """40m SOS optic: fused-silica cylinder, symmetry axis along the beam (x)."""

    radius_m: float = 0.075 / 2
    thickness_m: float = 0.025
    density_kg_m3: float = 2200.0

    @property
    def mass_kg(self) -> float:
        return self.density_kg_m3 * math.pi * self.radius_m**2 * self.thickness_m

    @property
    def I_roll(self) -> float:
        """About the optical axis x (roll): I = m R^2 / 2."""
        return 0.5 * self.mass_kg * self.radius_m**2

    @property
    def I_pitch(self) -> float:
        """Transverse axis (pitch): I = m R^2 / 4 + m H^2 / 12."""
        return (0.25 * self.mass_kg * self.radius_m**2
                + self.mass_kg * self.thickness_m**2 / 12.0)

    @property
    def I_yaw(self) -> float:
        """Transverse axis (yaw) — equal to pitch for a cylinder."""
        return self.I_pitch


@dataclass(frozen=True)
class SOSSuspension:
    """Wire-loop suspension parameters (those T000134 cannot supply for the 40m)."""

    wire_length_m: float       # l  — break-off to optic
    breakoff_m: float          # b  — wire attachment height above the CoM
    wire_sep_m: float          # d  — separation of the two vertical wire runs (in y)
    r1r2_m2: float             # R1*R2 — top x bottom wire half-separations (yaw torsion)
    k_vert_N_per_m: float      # k_v — total vertical wire stiffness


def _lp_block(l: float, b: float, optic: SOSOptic) -> np.ndarray:
    """The coupled longitudinal-pitch 2x2 stiffness block, in T000134's form.

    Wire break-off a height ``b`` above the CoM couples L and P: a longitudinal
    displacement tilts the optic and vice versa. Rows/cols are ordered ``[L, P]``.
    """
    w_L2 = G / l
    w_P2 = optic.mass_kg * G * b * (l + b) / (optic.I_pitch * l)
    return np.array([[w_L2,          -w_L2 * b],
                     [-w_P2 / (l + b), w_P2]])


def _lp_freqs(l: float, b: float, optic: SOSOptic) -> tuple[float, float]:
    """Eigenfrequencies [Hz] of the coupled L-P block, sorted descending (L first)."""
    lam = np.linalg.eigvals(_lp_block(l, b, optic))
    f = np.sort(np.sqrt(np.abs(lam)) / (2 * math.pi))[::-1]
    return float(f[0]), float(f[1])


def fit_suspension(optic: SOSOptic | None = None,
                   measured: dict[str, float] | None = None) -> SOSSuspension:
    """Pin the suspension parameters so the model reproduces the measured modes.

    Five of the six DOF are used as targets:

    * ``l``, ``b``  <- the **coupled** L-P pair (solved numerically, since the L-P coupling
      shifts both eigenvalues off their uncoupled values by a few tenths of a percent).
    * ``k_v``       <- V, via ``omega_V^2 = k_v / m``.
    * ``d``         <- R, via ``omega_R^2 = k_v d^2 / (4 I_roll)``.
    * ``R1*R2``     <- Y, via ``omega_Y^2 = m g R1 R2 / (I_yaw l)`` (T000134's torsion form).

    ``T`` (side) is deliberately *not* fitted — ``omega_T^2 = g / (l + b)`` follows from the
    already-pinned ``l`` and ``b``, so it is an independent check on the construction.
    """
    optic = optic or SOSOptic()
    measured = measured or MEASURED_MODES_HZ
    m = optic.mass_kg

    f_L, f_P = measured["L"], measured["P"]

    # Uncoupled analytic values are the initial guess; then solve the coupled 2x2 exactly.
    l0 = G / (2 * math.pi * f_L) ** 2
    w_P2 = (2 * math.pi * f_P) ** 2
    # m g b^2 + m g l b - I_P l w_P^2 = 0  ->  positive root
    b0 = (-m * G * l0 + math.sqrt((m * G * l0) ** 2
                                 + 4 * m * G * optic.I_pitch * l0 * w_P2)) / (2 * m * G)

    def residual(v):
        l, b = v
        fL, fP = _lp_freqs(abs(l), abs(b), optic)
        return [fL - f_L, fP - f_P]

    l, b = (abs(v) for v in fsolve(residual, [l0, b0], full_output=False))

    k_v = m * (2 * math.pi * measured["V"]) ** 2
    d = 2.0 * math.sqrt(optic.I_roll * (2 * math.pi * measured["R"]) ** 2 / k_v)
    r1r2 = (2 * math.pi * measured["Y"]) ** 2 * optic.I_yaw * l / (m * G)

    return SOSSuspension(wire_length_m=l, breakoff_m=b, wire_sep_m=d,
                         r1r2_m2=r1r2, k_vert_N_per_m=k_v)


def stiffness_matrix(optic: SOSOptic, susp: SOSSuspension) -> np.ndarray:
    """6x6 ``omega^2``-like matrix in the L T V R P Y basis.

    Only the L-P pair is coupled. T-R coupling is neglected: side sits at ~1 Hz and roll at
    ~22.6 Hz, so the induced shift is O((f_T/f_R)^2) ~ 0.2% — below the fidelity of the
    parameters themselves. Revisit if a measured T-R cross-coupling ever contradicts it.
    """
    l, b = susp.wire_length_m, susp.breakoff_m
    m = optic.mass_kg
    K = np.zeros((6, 6))

    lp = _lp_block(l, b, optic)
    K[_IDX["L"], _IDX["L"]] = lp[0, 0]
    K[_IDX["L"], _IDX["P"]] = lp[0, 1]
    K[_IDX["P"], _IDX["L"]] = lp[1, 0]
    K[_IDX["P"], _IDX["P"]] = lp[1, 1]

    K[_IDX["T"], _IDX["T"]] = G / (l + b)                                  # side pendulum
    K[_IDX["V"], _IDX["V"]] = susp.k_vert_N_per_m / m                      # wire stretch
    K[_IDX["R"], _IDX["R"]] = (susp.k_vert_N_per_m * susp.wire_sep_m**2
                               / (4 * optic.I_roll))                       # wires at +-d/2
    K[_IDX["Y"], _IDX["Y"]] = m * G * susp.r1r2_m2 / (optic.I_yaw * l)     # wire torsion
    return K


def build_plant(optic: SOSOptic | None = None,
                susp: SOSSuspension | None = None,
                *, structural_q: float = DEFAULT_STRUCTURAL_Q) -> control.StateSpace:
    """Continuous 6-in / 6-out, 12-state SOS plant as a ``control.StateSpace``.

    States are ``[q, qdot]`` with ``q`` in the L T V R P Y basis. Inputs are the per-DOF
    force/torque; outputs are the per-DOF displacement/angle.
    """
    optic = optic or SOSOptic()
    susp = susp or fit_suspension(optic)

    K = stiffness_matrix(optic, susp)
    # Per-mode velocity damping gamma = omega / Q, from each DOF's diagonal stiffness.
    gamma = np.sqrt(np.abs(np.diag(K))) / float(structural_q)

    Z, I6 = np.zeros((6, 6)), np.eye(6)
    A = np.block([[Z, I6], [-K, -np.diag(gamma)]])

    inertia = np.array([optic.mass_kg, optic.mass_kg, optic.mass_kg,
                        optic.I_roll, optic.I_pitch, optic.I_yaw])
    B = np.vstack([Z, np.diag(1.0 / inertia)])
    C = np.hstack([I6, Z])
    D = np.zeros((6, 6))

    return control.ss(A, B, C, D)


def inertia_vector(optic: SOSOptic) -> np.ndarray:
    """Generalized inertia per DOF in L T V R P Y order (mass for translations, moment for
    rotations) — the metric that makes eigenvector components comparable."""
    return np.array([optic.mass_kg, optic.mass_kg, optic.mass_kg,
                     optic.I_roll, optic.I_pitch, optic.I_yaw])


def labelled_modes(sys: control.StateSpace,
                   optic: SOSOptic | None = None) -> dict[str, tuple[float, float]]:
    """``{DOF: (f0_hz, Q)}``, each mode assigned to the DOF carrying most of its energy.

    Modal energy is ``M_ii * |v_i|^2``, **not** ``|v_i|^2``. The raw eigenvector mixes metres
    and radians, which are not comparable: the 1 Hz longitudinal mode of this plant has a
    larger pitch component than longitudinal component in raw units (0.387 m vs 1 rad) and a
    naive ``argmax`` mislabels it as pitch. Weighting by the generalized inertia makes the
    comparison physical — there the same mode is ~370x longitudinal.
    """
    optic = optic or SOSOptic()
    w2 = inertia_vector(optic)
    w, v = np.linalg.eig(np.asarray(sys.A, float))
    out: dict[str, tuple[float, float]] = {}
    for i, z in enumerate(w):
        if z.imag <= 1e-9:
            continue
        energy = w2 * np.abs(v[:6, i]) ** 2
        dof = DOFS[int(np.argmax(energy))]
        f0 = abs(z) / (2 * math.pi)
        Q = abs(z) / (-2 * z.real) if z.real < 0 else float("inf")
        out[dof] = (float(f0), float(Q))
    return out


def modes_hz(sys: control.StateSpace) -> list[tuple[float, float]]:
    """Oracle mode table ``[(f0_hz, Q), ...]`` from the plant's conjugate-pair eigenvalues."""
    out = []
    for z in np.linalg.eigvals(np.asarray(sys.A, float)):
        if z.imag <= 1e-9:
            continue
        f0 = abs(z) / (2 * math.pi)
        Q = abs(z) / (-2 * z.real) if z.real < 0 else float("inf")
        out.append((float(f0), float(Q)))
    return sorted(out)
